---
title: "Matrix Creation Example"
author: "Alex Sanchez"
date: "June 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Example of a matrix for a two x two design

```{r}
myValues2 <- c(c(1,1,1,0,0,0,1,1,1,0,0,0), 
              c(0,0,0,1,1,1,0,0,0,1,1,1), 
              c(1,1,1,1,1,1,0,0,0,0,0,0), 
              c(0,0,0,0,0,0,1,1,1,1,1,1))
myMatrix2 <- matrix(myValues2, ncol=4, byrow=F)
colnames(myMatrix2) <- c("grp.1.1", "grp.1.2", "grp.2.1", "grp.2.2")
rownames(myMatrix2) <- paste("sample", 
                             c(paste(1,1,1:3, sep="_"),
                               paste(1,2,1:3, sep="_"),
                               paste(2,1,1:3, sep="_"),
                               paste(2,2,1:3, sep="_")),sep=".")
myMatrix2
```

# Example of a matrix for a 1 factor design

```{r}
myValues <- c(c(1,1,1,0,0,0,0,0,0,0,0,0), 
              c(0,0,0,1,1,1,0,0,0,0,0,0), 
              c(0,0,0,0,0,0,1,1,1,0,0,0), 
              c(0,0,0,0,0,0,0,0,0,1,1,1))
myMatrix <- matrix(myValues, ncol=4, byrow=F)
colnames(myMatrix) <- paste("grp", 1:4, sep=".")
rownames(myMatrix) <- paste("sample", 
                             c(rep(1,3),rep(2,3), rep(3,3), rep(4,3)),
                             rep(1:3,4), sep=".")
myMatrix
```

# Comparing groups: Contrast matrix

```{r}
library(limma)
contMat <- makeContrasts(First_Sec=grp.1-grp.2,
                       Third_fourth=grp.3-grp.4,
                       First_Third=grp.1-grp.3,
                       levels=myMatrix)
contMat
```

